Create new helm chart for Zulip
greenhost/docker-zulip pull request #1
Opened 2021-11-18 16:50 UTC by mrtndwrd

2021-11-19 13:48 UTC, varac requested changes
Besides my comments, looks good!

2021-11-19 13:48 UTC, varac commented on kubernetes/chart/zulip/values-local.yaml.example
> +  memcachedPassword: set-secure-password
Even though I see your good intention in the comment at the top of this file I think it's not a good practice to set default passwords, even in a `values-local.yaml.example` file. Please comment them at least so users won't make the mistake of copying this file and forgetting to change a default password.

2021-11-19 13:48 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +
Please add an icon:

```suggestion
icon: https://raw.githubusercontent.com/zulip/zulip/main/static/images/logo/zulip-icon-square.svg
```

```
❯ helm lint             
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

2021-11-19 13:48 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +description: zulipchat
```suggestion
description: A chat for distributed teams which combines the immediacy of real-time chat with an email threading model. With Zulip, you can catch up on important conversations while ignoring irrelevant ones. 
```

2021-11-19 13:48 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +appVersion: "4.7-0"
The GH release page only states `4.7`

```suggestion
appVersion: "4.7"
```

2021-11-19 13:48 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +
```suggestion
sources:
  - https://github.com/zulip/zulip
  - https://github.com/zulip/docker-zulip
  - https://hub.docker.com/r/zulip/docker-zulip
```

2021-11-19 14:01 UTC, varac requested changes

2021-11-19 14:01 UTC, varac commented on kubernetes/chart/zulip/values-local.yaml.example
> +  repository: open.greenhost.net:4567/stackspin/stackspin/zulip
I'd use the official image here.

2021-11-19 14:01 UTC, varac commented on kubernetes/chart/zulip/templates/NOTES.txt
> +  http://{{ .host }}
```suggestion
  https://{{ .host }}
```

2021-11-19 14:01 UTC, varac commented on kubernetes/chart/zulip/templates/NOTES.txt
> +
I test-installed the chart, so far so good, but I couldn't succeed with creating a realm:

```
❯ kubectl -n zulip exec -it $(kubectl get pods --namespace zulip -l "app=zulip,release=zulip" -o jsonpath="{.items[0].metadata.name}") -c zulip /home/zulip/deployments/current/manage.py generate_realm_creation_link

error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}


kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: arguments in resource/name form may not have more than one slash
```

2021-11-22 09:49 UTC, varac requested changes
Nice, please have a look at my two comments which were not addressed in you latest commits.

2021-11-22 09:49 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +appVersion: "4.7-0"
What about this change ? I don't see it in your last 2 commits

2021-11-22 09:49 UTC, varac commented on kubernetes/chart/zulip/templates/NOTES.txt
> +  http://{{ .host }}
What about this change ?

2021-11-22 09:53 UTC, mrtndwrd reviewed
forgotten comments

2021-11-22 09:53 UTC, mrtndwrd commented on kubernetes/chart/zulip/Chart.yaml
> +appVersion: "4.7-0"
The [Docker tag I'm installing is `4.7-0`](https://github.com/greenhost/docker-zulip#welcome-to-docker-zulip), so I prefer to keep it like this to make that clear.

2021-11-22 09:53 UTC, mrtndwrd commented on kubernetes/chart/zulip/templates/NOTES.txt
> +  http://{{ .host }}
Although I like https, `http` will always work, whereas `https` here will only work if people have added a cert-manager annotation to their ingress (or another way to enable TLS), which is not the default.

2021-11-22 09:59 UTC, varac commented on kubernetes/chart/zulip/Chart.yaml
> +appVersion: "4.7-0"
OK!

2021-11-22 09:59 UTC, varac commented on kubernetes/chart/zulip/templates/NOTES.txt
> +  http://{{ .host }}
Agreed

2021-11-22 10:00 UTC, varac commented
If you see a merge button please hit it, I don't :P

2021-11-22 10:06 UTC, merged